<a href="https://colab.research.google.com/github/erc-kluijtmans/Machine-Learning/blob/master/Simple_Transformer_Language_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Resources
https://github.com/huggingface/blog/blob/main/notebooks/02_how_to_generate.ipynb





https://www.youtube.com/watch?v=-QH8fRhqFHM&ab_channel=JayAlammar


In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 18.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 46.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 7.9 MB/s eta 0:00:00


In [2]:
from transformers import GPT2Tokenizer, GPT2Model, GPT2LMHeadModel
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2',pad_token_id=tokenizer.eos_token_id)


Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/548M [00:00<?, ?B/s]

In [3]:
text = "I enjoy walking with my cute dog"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=50, do_sample=False)

# Print the output
print('\n',tokenizer.decode(output[0]))


 I enjoy walking with my cute dog, but I'm not sure if I'll ever be able to walk with my dog. I'm not sure if I'll ever be able to walk with my dog.

I'm not sure if I'll


In [ ]:
# Print the token ides (of the input and output)
output

tensor([[18217,  4749, 19272,     1,   290]])

## From words to vectors and back

In [ ]:
# Print the input token ids
text = "The color of a banana is"
input = tokenizer(text, return_tensors="pt")['input_ids']
input

tensor([[  464,  3124,   286,   257, 25996,   318]])

In [ ]:
tokenizer.convert_ids_to_tokens(input[0])

['The', 'Ġcolor', 'Ġof', 'Ġa', 'Ġbanana', 'Ġis']

## Breathe meaning into numbers (Embedding)

In [ ]:
# This is the embedding matrix of the model
model.transformer.wte # Dimensions are: (Number of tokens in vocabulary, dimension of model)

Embedding(50257, 768)

In [ ]:
import torch

In [ ]:
# Get the embedding vector of token # 464 ('The')
model.transformer.wte(torch.tensor(464))

tensor([-6.8623e-02, -2.0298e-02,  6.4471e-02, -6.2085e-02, -1.1352e-01,
        -6.2337e-02, -2.1719e-01, -2.9746e-02,  3.8659e-03, -1.0428e-02,
        -3.7695e-02,  2.6119e-02,  7.6351e-02, -3.0347e-02,  1.0757e-01,
        -1.8893e-02,  5.6020e-02,  5.1582e-02, -2.4212e-02,  1.3702e-01,
        -4.6440e-02,  2.9035e-02, -5.2729e-02,  3.9311e-02, -5.7571e-03,
        -3.4328e-02,  5.1317e-02, -2.7329e-02, -6.9629e-02,  1.7323e-02,
        -3.6435e-02, -5.7844e-02, -5.8048e-02,  6.3479e-02, -4.3887e-02,
        -3.6068e-02, -3.1934e-01,  7.1641e-02,  8.3253e-02, -2.7106e-02,
         1.1349e-01, -8.6667e-02, -8.2599e-02, -6.6505e-02,  5.5040e-02,
        -5.3986e-03,  1.3219e-02,  2.9831e-02,  6.5156e-02, -1.6650e-01,
        -7.9967e-03,  3.0170e-02,  2.6669e-02,  7.5700e-02,  6.9849e-02,
        -3.6223e-01, -4.4599e-02, -3.8639e-03, -1.1880e-02, -4.6784e-03,
        -4.1325e-02, -3.8791e-02,  3.1904e-02, -2.1479e-02, -2.5077e-01,
         1.7805e-02,  3.9195e-04, -3.6580e-02,  3.1

In [10]:
text = "Describe the best way to come to Avans Breda from Amsterdam"
# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")


# activate beam search and early_stopping
beam_output = model.generate(
    input,  
    max_length=100, 
    num_beams=5, 
    no_repeat_ngram_size=2,
    early_stopping=True
)

# Run the model
print("Output:\n" + 100 * '-')
print(tokenizer.decode(beam_output[0], skip_special_tokens=True))

Output:
----------------------------------------------------------------------------------------------------
Describe the best way to come to Avans Breda from Amsterdam.

"I've always wanted to go to Amsterdam, but I didn't know how to get there. I had no idea what I was going to be doing, so I decided to stay in Amsterdam for a while. It was a great experience, and I'm really glad I did it."
